{{- include "common-library.deployment" (dict "globals" . "override" "acme-dns.deployment") -}}
{{- define "acme-dns.deployment" -}}
{{- end -}}
{{- define "acme-dns.container" -}}
{{- end -}}
        
          
