apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ default (tpl "{{ .Values.common.name }}-deploy" $ ) .Values.deployment.name}}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- range $name, $value := .Values.common.labels}}
      {{ $name }}: {{ $value}}
    {{- end}}
    {{- range $name, $value := .Values.deployment.labels}}
      {{ $name }}: {{ $value}}
    {{- end}}
spec:
  replicas: {{ default 1 .Values.deployment.replicas }}
  selector:
    matchLabels:
    {{- range $name, $value := .Values.common.labels}}
      {{ $name }}: {{ $value}}
    {{- end}}
    {{- range $name, $value := .Values.pod.labels}}
      {{ $name }}: {{ $value}}
    {{- end}}
  template:
    metadata:
      name: {{ default (tpl "{{ .Values.common.name }}-pod" $ ) .Values.pod.name}}
      namespace: {{ .Release.Namespace }}
      labels:
      {{- range $name, $value := .Values.common.labels}}
        {{ $name }}: {{ $value}}
      {{- end}}
      {{- range $name, $value := .Values.pod.labels}}
        {{ $name }}: {{ $value}}
      {{- end}}
    spec:
      containers:
        - name: acme-dns
          image: joohoi/acme-dns:{{ .Chart.AppVersion }}
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: dns-port-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-port-udp
              containerPort: 53 
              protocol: UDP
            - name: http-port
              containerPort: 80
            - name: https-port
              containerPort: 443
          volumeMounts:
            - mountPath: /etc/acme-dns/config.cfg
              name: config
              subPath: config.cfg
      volumes:
        - name: config
          configMap:
            name: {{ default (tpl "{{ .Values.common.name }}-config" $ ) .Values.configMap.name}}
          
