annotations: {}
apiVersion: v2
appVersion: v1.0
dependencies:
  - name: common-library
    repository: file://../common-library
    version: 0.0.1
deprecated: false
description: Simple ACME-DNS server helm chart
home: The URL of this projects home page (optional)
icon: https://www.svgrepo.com/show/379134/dns.svg
keywords:
  - acme
  - letsencrypt
  - dns
kubeVersion: ""
maintainers:
  - email: joern.krenzer@gmx.de
    name: jkrenzer
    url: https://github.com/jkrenzer
name: acme-dns
sources:
  - https://github.com/joohoi/acme-dns
type: application
version: 0.0.3
