{{- include "common-library.configMap" (dict "globals" . "override" "mailserver.configMap") -}}
{{- define "mailserver.configMap" -}}
data:
  postfix-accounts.cf: |-
    {{ range $account := .Values.config.accounts -}}
    {{ tpl $account.email $ -}}|{BLF-CRYPT}{{- tpl $account.password $ | bcrypt }}
    {{- end }}
  TrustedHosts: |-
    {{- tpl .Values.config.trustedHosts . | nindent 4 }}
{{- end }}

