{{- include "common-library.deployment" (dict "globals" . "override" "mailserver.deployment") -}}
{{- define "mailserver.deployment" -}}
spec:
  template:
    spec:
      volumes:
        - name: pv
          persistentVolumeClaim:
            claimName: {{ tpl .Values.persistentVolumeClaim.name . }}
        - name: config
          configMap:
            name: {{ tpl .Values.configMap.name . }}
        {{- if .Values.config.enableTls }}
        - name: certs
          secret:
            secretName: {{ tpl .Values.certSecret.name . }}
        {{- end }}
        - name: tmp-files
          emptyDir: {}
{{- end -}}
{{- define "mailserver.container" -}}
{{ if .Values.config.ldap.enable -}}
envFrom:
  - secretRef:
      name: {{ tpl .Values.secret.name . }} 
{{- end }}
volumeMounts:
  - mountPath: /tmp/docker-mailserver/postfix-accounts.cf
    name: config
    subPath: postfix-accounts.cf
  - mountPath: /tmp/docker-mailserver/opendkim
    name: pv
    subPath: opendkim-tmp
  - mountPath: /var/mail
    name: pv
    subPath: data
  - mountPath: /var/mail-state
    name: pv
    subPath: state
  - mountPath: /var/log/mail
    name: pv
    subPath: log
  - mountPath: /secrets/ssl/rsa
    readOnly: true
    {{- if .Values.config.enableTls }}
    name: certs
    {{- else }}
    name: pv
    subPath: certs
    {{ end }}
  - name: tmp-files
    mountPath: /tmp
{{- end -}}