apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ tpl .Values.deployment.name . }}
  namespace: {{ .Values.common.namespace }}
  labels: {{ mustMerge .Values.deployment.labels .Values.common.labels | toYaml | nindent 4 }}
  annotations: {{ mustMerge .Values.deployment.annotations .Values.common.annotations | toYaml | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels: {{ mustMerge .Values.pod.labels .Values.common.labels | toYaml | nindent 6 }}
  template:
    metadata:
      name: {{ tpl .Values.pod.name . }}
      namespace: {{ .Values.common.namespace }}
      labels: {{ mustMerge .Values.pod.labels .Values.common.labels | toYaml | nindent 8 }}
      annotations: {{ mustMerge .Values.pod.annotations .Values.common.annotations | toYaml | nindent 8 }}
    spec:
      containers:
        - name: mailserver
          image: mailserver/docker-mailserver:13.3.0
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            privileged: false
            capabilities:
              add:
                # file permission capabilities
                - CHOWN
                - FOWNER
                - MKNOD
                - SETGID
                - SETUID
                - DAC_OVERRIDE
                # network capabilities
                - NET_ADMIN  # needed for F2B
                - NET_RAW    # needed for F2B
                - NET_BIND_SERVICE
                # miscellaneous  capabilities
                - SYS_CHROOT
                - KILL
              drop: [ALL]
            seccompProfile:
              type: RuntimeDefault
          resources: {{ .Values.deployment.resources | toYaml | nindent 12 }}
          ports: 
            - containerPort: 25
              hostPort: 25
              name: transfer-port
              protocol: TCP
            - containerPort: 143
              hostPort: 143
              name: imap-port
              protocol: TCP
            - containerPort: 465
              hostPort: 465
              name: smtps-port
              protocol: TCP
            - containerPort: 587
              hostPort: 587
              name: smtp-port
              protocol: TCP
            - containerPort: 993
              hostPort: 993
              name: imaps-port
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ tpl .Values.configMap.name . }}
            {{ if .Values.config.ldap.enable }}
            - secretRef:
                name: {{ tpl .Values.secret.name . }} 
            {{ end }}
          volumeMounts:
            - mountPath: /tmp/docker-mailserver/opendkim
              name: pv
              subPath: opendkim-tmp
            - mountPath: /var/mail
              name: pv
              subPath: data
            - mountPath: /var/mail-state
              name: pv
              subPath: state
            - mountPath: /var/log/mail
              name: pv
              subPath: log
            - mountPath: /secrets/ssl/rsa
              readOnly: true
              {{- if .Values.config.enableTls }}
              name: certs
              {{- else }}
              name: pv
              subPath: certs
              {{ end }}
            - name: tmp-files
              mountPath: /tmp
      volumes:
        - name: pv
          persistentVolumeClaim:
            claimName: {{ tpl .Values.persistentVolumeClaim.name . }}
        {{- if .Values.config.enableTls }}
        - name: certs
          secret:
            secretName: {{ tpl .Values.certSecret.name . }}
        {{- end }}
        - name: tmp-files
          emptyDir: {}
