{{ if .Values.config.ldap.enable }}
---
apiVersion: v1
data:
  LDAP_BIND_DN: {{ tpl .Values.config.ldap.bindDn . | required "config.ldap.bindDn is required!" | b64enc | quote }}
  LDAP_BIND_PW: {{ tpl .Values.config.ldap.bindPassword . | required "config.ldap.bindPassword is required!" | b64enc | quote }}
kind: Secret
metadata:
  name: {{ tpl .Values.secret.name . }}
  namespace: {{ .Values.common.namespace }}
  labels: {{ mustMerge .Values.secret.labels .Values.common.labels | toYaml | nindent 4 }}
  annotations: {{ mustMerge .Values.secret.annotations .Values.common.annotations | toYaml | nindent 4 }}
type: Opaque
{{ end }}