{{- include "common-library.secret" (dict "globals" . "override" "mailserver.secret") -}}
{{- define "mailserver.secret" -}}
data:
  {{ if .Values.config.ldap.enable -}}
  LDAP_BIND_DN: {{ tpl .Values.config.ldap.bindDn . | required "config.ldap.bindDn is required!" | b64enc | quote }}
  LDAP_BIND_PW: {{ tpl .Values.config.ldap.bindPassword . | required "config.ldap.bindPassword is required!" | b64enc | quote }}
  {{- end }}
{{- end }}