{{- if .Values.serviceAccount.create -}}
{{- include "common-library.serviceAccount" (dict "globals" . "override" "mailserver.serviceAccount") -}}
{{- end -}}
{{- define "mailserver.serviceAccount" -}}
{{- end -}}