---
apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.service.name . }}
  namespace: {{ .Values.common.namespace }}
  labels: {{ mustMerge .Values.service.labels .Values.common.labels | toYaml | nindent 4}}
  annotations: {{ mustMerge .Values.service.annotations .Values.common.annotations | toYaml | nindent 4 }}
spec:
  selector:
    app: mailserver
  ports:
    - name: transfer-port
      port: 25
      targetPort: transfer-port
      protocol: TCP
    - name: imap-port    
      port: 143
      targetPort: imap-port
      protocol: TCP
    - name: smtp-port
      port: 587
      targetPort: smtp-port
      protocol: TCP
    - name: imaps-port
      port: 993
      targetPort: imaps-port
      protocol: TCP
  selector: {{ tpl .Values.service.selectors . | nindent 4}}
