{{- if .Values.storageClass.create -}}
{{- include "common-library.storageClass" (dict "globals" . "override" "mailserver.storageClass") -}}
{{- end -}}
{{- define "mailserver.storageClass" -}}
{{- end }}