{{ if .Values.certManager.enable }}
{{- include "common-library.certificateIssuer" (dict "globals" . "override" "keycloak.certificateIssuer") -}}
{{- end -}}
{{- define "keycloak.certificateIssuer" -}}
{{- end -}}