{{- include "common-library.configMap" (dict "globals" . "override" "keycloak.configMap") -}}
{{- define "keycloak.configMap" -}}
data:
  {{- range $name, $value := .Values.environmentVars }}
    {{ $name | upper }}: {{ tpl $value $ }}
  {{- end -}}
{{- end -}}
{{ if .Values.config.kerberos.enable -}}
---
{{- include "common-library.configMap" (dict "globals" . "override" "keycloak.kerberosConfigMap") -}}
{{- end -}}
{{- define "keycloak.kerberosConfigMap" -}}
{{- $commons  := .Values.common  -}}
{{- $locals   := .Values.kerberosConfigMap -}}
{{- $metadata := include "common-library.makeMetadata" (dict "locals" $locals "commons" $commons "globals" .) -}}
data:
  krb5.conf: |-
    [domain_realm]
    .{{ .Values.config.kerberos.domain | required "config.kerberos.domain is required!"}} = {{ .Values.config.kerberos.domain | upper }}
    {{ .Values.config.kerberos.domain }} = {{ .Values.config.kerberos.domain | upper }}
kind: ConfigMap
metadata: {{ $metadata | nindent 2 }}
type: Opaque
{{- end -}}