{{- include "common-library.deployment" (dict "globals" . "override" "keycloak.deployment") -}}
{{- define "keycloak.deployment" -}}
{{- end -}}
{{- define "keycloak.container" -}}
args: 
  - start-dev
  - "--spi-vault-file-key-resolvers=REALM_UNDERSCORE_KEY,KEY_ONLY"
  {{ if .Values.config.tls.enable -}}
  - "--https-certificate-file=/secrets/ssl/rsa/tls.crt" 
  - "--https-certificate-key-file=/secrets/ssl/rsa/tls.key"
  {{- end }}
envFrom:
  - configMapRef:
      name: keycloak-config
  - secretRef:
      name: keycloak-secret
{{- end -}}