{{- include "common-library.deployment" (dict "globals" . "override" "keycloak.deployment") -}}
{{- define "keycloak.deployment" -}}
spec:
  template:
    spec:
      containers:
        - args: 
            - start-dev
            - "--spi-vault-file-key-resolvers=REALM_UNDERSCORE_KEY,KEY_ONLY"
            {{ if .Values.config.tls.enable -}}
            - "--https-certificate-file=/secrets/ssl/rsa/tls.crt" 
            - "--https-certificate-key-file=/secrets/ssl/rsa/tls.key"
            {{- end }}
          envFrom:
            - configMapRef:
                name: keycloak-config
            - secretRef:
                name: keycloak-secret
          image: quay.io/keycloak/keycloak:{{ .Chart.AppVersion }}
          name: keycloak
          ports:
            - containerPort: 8080
              name: http
            {{ if .Values.config.tls.enable -}}
            - containerPort: 8443
              name: https
            {{- end }}
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 12
          volumeMounts:
            - mountPath: /opt/keycloak/data/import
              name: pv
              subPath: import
            - mountPath: /opt/keycloak/providers
              name: pv
              subPath: providers
            - mountPath: /opt/keycloak/themes
              name: pv
              subPath: themes
            - mountPath: /opt/keycloak/conf
              name: pv
              subPath: conf
            - mountPath: /secrets/ssl/rsa
              readOnly: true
              {{- if .Values.config.tls.enable }}
              name: certs
              {{- else }}
              name: pv
              subPath: certs
              {{ end }}
      securityContext:
        runAsUser: 1000
      volumes:
        - name: pv
          persistentVolumeClaim:
            claimName: {{ tpl .Values.persistentVolumeClaim.name . }}
        {{- if .Values.config.tls.enable }}
        - name: certs
          secret:
            secretName: {{ tpl .Values.certSecret.name . }}
        {{- end }}
        - name: tmp-files
          emptyDir: {}
{{- end -}}
