apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ tpl .Values.deployment.name . }}
  namespace: {{ .Values.common.namespace }}
  labels: {{ mustMerge .Values.deployment.labels .Values.common.labels | toYaml | nindent 4 }}
  annotations: {{ mustMerge .Values.deployment.annotations .Values.common.annotations | toYaml | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels: {{ mustMerge .Values.pod.labels .Values.common.labels | toYaml | nindent 6 }}
  template:
    metadata:
      name: {{ tpl .Values.pod.name . }}
      namespace: {{ .Values.common.namespace }}
      labels: {{ mustMerge .Values.pod.labels .Values.common.labels | toYaml | nindent 8 }}
      annotations: {{ mustMerge .Values.pod.annotations .Values.common.annotations | toYaml | nindent 8 }}
    spec:
      containers:
        - args: 
            - start-dev
            - "--spi-vault-file-key-resolvers=REALM_UNDERSCORE_KEY,KEY_ONLY"
            {{ if .Values.config.tls.enable -}}
            - "--https-certificate-file=/certs/tls.crt" 
            - "--https-certificate-key-file=/certs/tls.key"
            {{- end }}
          envFrom:
            - configMapRef:
                name: keycloak-config
            - secretRef:
                name: keycloak-secret
          image: quay.io/keycloak/keycloak:23.0.4
          name: keycloak
          ports:
            - containerPort: 8080
              name: http
            {{ if .Values.config.tls.enable -}}
            - containerPort: 8443
              name: https
            {{- end }}
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
          volumeMounts:
            - mountPath: /opt/keycloak/data/import
              name: keycloak-pv
              subPath: import
            - mountPath: /opt/keycloak/providers
              name: keycloak-pv
              subPath: providers
            - mountPath: /opt/keycloak/themes
              name: keycloak-pv
              subPath: themes
            - mountPath: /opt/keycloak/conf
              name: keycloak-pv
              subPath: conf
            #- mountPath: /opt/keycloak/lib/quarkus
            #  name: keycloak-pv
            #  subPath: quarkus-state
      securityContext:
        runAsUser: 1000
      volumes:
        - name: keycloak-pv
          persistentVolumeClaim:
            claimName: keycloak-pvc
