{{- include "common-library.ingress" (dict "globals" . "override" "keycloak.ingress") -}}
{{- define "keycloak.ingress" -}}
spec:
  rules:
    - host: {{ .Values.config.domain }}
      http:
        paths:
          - backend:
              service:
                name: keycloak
                port:
                  {{ if .Values.config.tls.enable -}}
                  number: 8080
                  {{ else -}}
                  number: 8443
                  {{- end }}
            path: /
            pathType: Prefix
{{- end -}}
