{{- if .Values.persistentVolume.create -}}
{{- include "common-library.persistentVolume" (dict "globals" . "override" "keycloak.persistentVolume") -}}
{{- end -}}
{{- define "keycloak.persistentVolume" -}}
{{- end -}}