{{- if .Values.persistentVolume.create -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ tpl .Values.persistentVolume.name . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ mustMerge .Values.persistentVolume.labels .Values.common.labels | toYaml | nindent 4}}
  annotations: {{ mustMerge .Values.persistentVolume.annotations .Values.common.annotations | toYaml | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.storage.space }}
  volumeMode: {{ .Values.persistentVolume.volumeMode }}
  accessModes: {{ .Values.storage.accessModes | toYaml | nindent 4 }}
  persistentVolumeReclaimPolicy: {{ .Values.persistentVolume.reclaimPolicy }}
  storageClassName: {{ .Values.storage.storageClassName }}
  {{- if .Values.storage.local }}
  local: {{ .Values.storage.local | toYaml }}
  {{- end }}
  nodeAffinity:
    {{- if .Values.storage.hosts}}
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          {{- range $host := .Values.storage.hosts }}
          - {{ $host }}
          {{- end }}
    {{- else }}
    {}
    {{- end }}
{{- end }}