---
apiVersion: v1
data:
  KC_DB_PASSWORD: {{ .Values.config.db.password | required "config.db.password is required!" | b64enc | quote }}
  KEYCLOAK_ADMIN: {{ .Values.config.adminUser | required "config.adminUser is required!" | b64enc | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.config.adminPassword | required "config.adminPassword is required!" | b64enc | quote }}
  {{ if .Values.config.ldap.enable }}
  LDAP_BIND_DN: {{ .Values.config.ldap.bindDn | required "config.ldap.bindDn is required!" | b64enc | quote }}
  LDAP_BIND_PW: {{ .Values.config.ldap.bindPassword | required "config.ldap.bindPassword is required!" | b64enc | quote }}
  {{ end }}
  {{ if .Values.config.smtp.enable }}
  SMTP_USER_NAME: {{ .Values.config.smtp.user | required "config.smtp.user is required!" | b64enc | quote }}
  SMTP_PASSWORD: {{ .Values.config.smtp.password | required "config.smtp.password is required!" | b64enc | quote }}
  {{ end }}
kind: Secret
metadata:
  name: {{ tpl .Values.secret.name . }}
  namespace: {{ .Values.common.namespace }}
  labels: {{ mustMerge .Values.secret.labels .Values.common.labels | toYaml | nindent 4 }}
  annotations: {{ mustMerge .Values.secret.annotations .Values.common.annotations | toYaml | nindent 4 }}
type: Opaque
