{{- if .Values.serviceAccount.create -}}
{{- include "common-library.serviceAccount" (dict "globals" . "override" "keycloak.serviceAccount") -}}
{{- end -}}
{{- define "keycloak.serviceAccount" -}}
{{- end -}}