---
apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.service.name . }}
  namespace: {{ .Values.common.namespace }}
  labels: {{ mustMerge .Values.service.labels .Values.common.labels | toYaml | nindent 4}}
  annotations: {{ mustMerge .Values.service.annotations .Values.common.annotations | toYaml | nindent 4 }}
spec:
  selector:
    app: keycloak
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    {{ if .Values.config.tls.enable -}}
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
    {{- end }}
  selector: {{ tpl .Values.service.selectors . | nindent 4}}
