{{- if .Values.persistentVolume.create -}}
{{- include "common-library.persistentVolume" (dict "globals" . "override" "postgres.persistentVolume") -}}
{{- end -}}
{{- define "postgres.persistentVolume" -}}
{{- end -}}