apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ default (tpl "{{ .Values.common.name }}-pv" $ ) .Values.pv.name }}
  namespace: {{ .Values.common.namespace }}
  labels:
    {{- range $name, $value := .Values.common.labels}}
      {{ $name }}: {{ $value}}
    {{- end}}
    {{- range $name, $value := .Values.pv.labels}}
      {{ $name }}: {{ $value}}
    {{- end}}
spec:
  capacity:
    storage: {{ default "10Gi" .Values.storage.space }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: {{ .Values.storage.storageClassName }}
  {{- if .Values.storage.local.path }}
  local:
    path: {{ .Values.storage.local.path }}
  {{- end }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          {{- range $host := .Values.storage.hosts }}
          - {{ $host }}
          {{- end }}
