apiVersion: v1
data:
  password: {{ b64enc .Values.database.password }}
kind: Secret
metadata:
  name: {{ default (tpl "{{ .Values.common.name }}-secrets" $ ) .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- range $name, $value := .Values.common.labels}}
      {{ $name }}: {{ $value}}
    {{- end}}
    {{- range $name, $value := .Values.secret.labels}}
      {{ $name }}: {{ $value}}
    {{- end}}
type: Opaque
