{{- if .Values.serviceAccount.create -}}
{{- include "common-library.serviceAccount" (dict "globals" . "override" "postgres.serviceAccount") -}}
{{- end -}}
{{- define "postgres.serviceAccount" -}}
{{- end -}}