apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- range $name, $value := .Values.common.labels}}
      {{ $name }}: {{ $value}}
    {{- end}}
    {{- range $name, $value := .Values.service.labels}}
      {{ $name }}: {{ $value}}
    {{- end}}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    name: {{ .Values.service.name }}
    targetPort: {{ .Values.service.name }}
  selector:
    {{- range $name, $value := .Values.common.labels}}
      {{ $name }}: {{ $value}}
    {{- end}}
    {{- range $name, $value := .Values.pod.labels}}
      {{ $name }}: {{ $value}}
    {{- end}}
