annotations: {}
apiVersion: v2
appVersion: 26.0.5
dependencies:
  - name: common-library
    repository: file://../common-library
    version: 0.0.1
deprecated: false
description: Docker-Mailserver helm chart
home: https://www.keycloak.org/
icon: https://www.keycloak.org/resources/images/logo.svg
keywords:
  - postfix
  - dovecot
  - mail
kubeVersion: ""
maintainers:
  - email: joern.krenzer@gmx.de
    name: jkrenzer
    url: https://github.com/jkrenzer
name: keycloak
sources:
  - https://github.com/keycloak/keycloak
type: application
version: 0.1.0
