apiVersion: v2
name: keycloak
version: 0.1.0
kubeVersion: ""
description: Docker-Mailserver helm chart
type: application
keywords:
  - postfix
  - dovecot
  - mail
home: https://www.keycloak.org/
sources:
  - https://github.com/keycloak/keycloak
dependencies:
  - name: common-library
    version: 0.0.1
    repository: "file://../common-library"
maintainers:
  - name: jkrenzer
    email: joern.krenzer@gmx.de
    url: https://github.com/jkrenzer
appVersion: "26.0.5"
icon: https://www.keycloak.org/resources/images/logo.svg
deprecated: false
annotations: {}
