---
cert:
  annotations: {}
  dnsNames: []
  issuer: '{{ tpl .Values.certIssuer.name . }}'
  labels: {}
  name: '{{ .Values.common.name }}-cert'
certIssuer:
  annotations: {}
  labels: {}
  # Name is used as domain name by cert-manager internals, so has to be all lower-case!
  name: '{{ .Values.common.name }}-issuer'
certManager:
  enable: true
certSecret:
  annotations: {}
  labels: {}
  name: '{{ .Values.common.name }}-cert-secret'
  template: |
    labels: {{ mustMerge .Values.cert.labels .Values.common.labels | toYaml | nindent 2 }}
    test: null
common:
  annotations: {}
  labels:
    app: keycloak
  name: keycloak
config:
  adminPassword: '{{ randAlphaNum 32 }}'
  adminUser: '{{ randAlphaNum 8 }}'
  db:
    host: null
    name: null
    password: '{{ randAlphaNum 32 }}'
    type: dev-file
    user: null
  domain: keycloak
  kerberos:
    enable: false
  ldap:
    enable: false
    enable_tls: false
    host: localhost
  logLevel: info
  smtp:
    enable: false
  tls:
    enable: true
configMap:
  annotations: {}
  labels: {}
  name: '{{ .Values.common.name }}-config'
deployment:
  annotations: {}
  autoscaling:
    enable: false
    maxReplicas: 100
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  labels: {}
  name: '{{ .Values.common.name }}-deploy'
  replicas: 1
environmentVars:
  KC_DB: '{{ .Values.config.db.type | required ".config.db.type is required!" | quote }}'
  KC_DB_URL_DATABASE: '{{ .Values.config.db.name | quote }}'
  KC_DB_URL_HOST: '{{ .Values.config.db.host | quote }}'
  KC_DB_USERNAME: '{{ .Values.config.db.user | quote }}'
  KC_FEATURES: preview
  KC_HEALTH_ENABLED: '"true"'
  KC_HOSTNAME: '{{ .Values.config.domain | quote }}'
  KC_HTTP_HOST: 0.0.0.0
  KC_HTTP_MANAGEMENT_PORT: '"9000"'
  KC_HTTP_MANAGEMENT_RELATIVE_PATH: /
  KC_PROXY: edge
image:
  pullPolicy: IfNotPresent
  repository: quay.io/keycloak/keycloak
  tag: '{{ .Chart.AppVersion }}'
ingress:
  annotations:
    cert-manager.io/issuer: letsencrypt-http-issuer
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  class: nginx
  enable: true
  labels: {}
  name: '{{ .Values.common.name }}-ingress'
kerberosConfigMap:
  annotations: {}
  labels: {}
  name: '{{ .Values.common.name }}-kerberos-config'
livenessProbe:
  failureThreshold: 20
  httpGet:
    path: /health/live
    port: management-http
    scheme: '{{ if .Values.config.tls.enable -}}HTTPS{{- else -}}HTTP{{- end }}'
  initialDelaySeconds: 30
  periodSeconds: 5
persistentVolume:
  annotations: {}
  create: true
  labels: {}
  name: '{{ .Values.common.name }}-pv'
  reclaimPolicy: Delete
  volumeMode: Filesystem
persistentVolumeClaim:
  annotations: {}
  labels: {}
  name: '{{ .Values.common.name }}-pvc'
pod:
  annotations: {}
  labels: {}
  name: '{{ .Values.common.name }}-pod'
readinessProbe:
  failureThreshold: 20
  httpGet:
    path: /health/ready
    port: management-http
    scheme: '{{ if .Values.config.tls.enable -}}HTTPS{{- else -}}HTTP{{- end }}'
  initialDelaySeconds: 30
  periodSeconds: 5
resources:
  limits:
    cpu: 1500m
    memory: 4Gi
  requests:
    cpu: 600m
    memory: 2Gi
scripts:
  annotations: {}
  labels: {}
  name: '{{ .Values.common.name }}-scripts'
secret:
  annotations: {}
  labels: {}
  name: '{{ .Values.common.name }}-secret'
securityContext:
  runAsUser: 1000
service:
  annotations: {}
  labels: {}
  name: '{{ .Values.common.name }}-service'
  portName: http
  ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    - containerPort: 8443
      name: https
      protocol: TCP
      when: '{{ .Values.config.tls.enable | default "false" }}'
  selectors: '{{ mustMerge .Values.pod.labels .Values.common.labels | toYaml }}'
serviceAccount:
  annotations: {}
  create: true
  labels: {}
  name: '{{ .Values.common.name }}-sa'
startupProbe:
  failureThreshold: 20
  httpGet:
    path: /health/started
    port: management-http
    scheme: '{{ if .Values.config.tls.enable -}}HTTPS{{- else -}}HTTP{{- end }}'
  initialDelaySeconds: 30
  periodSeconds: 5
storage:
  accessModes:
    - ReadWriteMany
  local:
    basePath: /data
    path: '{{ .Values.storage.local.basePath }}/{{ .Values.common.name }}'
  space: 10Gi
  storageClassName: local-storage
  type: local
storageClass:
  annotations: {}
  create: false
  labels: {}
  name: '{{ .Values.storage.storageClassName }}'
  provisioner: kubernetes.io/no-provisioner
  volumeBindingMode: WaitForFirstConsumer
volumeMounts: []
volumes: []
