annotations: {}
apiVersion: v2
appVersion: "2.6"
dependencies:
  - name: common-library
    repository: file://../common-library
    version: 0.0.1
deprecated: false
description: Simple OpenLDAP helm chart based on Tiredofit's docker image
home: The URL of this projects home page (optional)
icon: https://www.svgrepo.com/show/511864/directory-search-1623.svg
keywords:
  - openldap
  - slapd
  - backup
kubeVersion: ""
maintainers:
  - email: joern.krenzer@gmx.de
    name: jkrenzer
    url: https://github.com/jkrenzer
name: openldap
sources:
  - https://github.com/tiredofit/docker-openldap
type: application
version: 0.0.3
