annotations: {}
apiVersion: v2
appVersion: 13.3.0
dependencies:
  - name: common-library
    repository: file://../common-library
    version: 0.0.1
deprecated: false
description: Docker-Mailserver helm chart
home: https://docker-mailserver.github.io/docker-mailserver/v13.3/
icon: https://avatars.githubusercontent.com/u/76868633?s=48&v=4
keywords:
  - postfix
  - dovecot
  - mail
kubeVersion: ""
maintainers:
  - email: joern.krenzer@gmx.de
    name: jkrenzer
    url: https://github.com/jkrenzer
name: docker-mailserver
sources:
  - https://github.com/docker-mailserver/docker-mailserver
type: application
version: 0.0.3
