{{- include "common-library.deployment" (dict "globals" . "override" "openldap.deployment") -}}
{{- define "openldap.deployment" -}}
{{- end -}}
{{- define "openldap.container" -}}
envFrom:
  - configMapRef:
      name: {{ tpl .Values.configMap.name . }}
{{- end }}