apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ tpl .Values.deployment.name . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ mustMerge .Values.deployment.labels .Values.common.labels | toYaml | nindent 4 }}
  annotations: {{ mustMerge .Values.deployment.annotations .Values.common.annotations | toYaml | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels: {{ mustMerge .Values.pod.labels .Values.common.labels | toYaml | nindent 6 }}
  template:
    metadata:
      name: {{ tpl .Values.pod.name . }}
      namespace: {{ .Release.Namespace }}
      labels: {{ mustMerge .Values.pod.labels .Values.common.labels | toYaml | nindent 8 }}
      annotations: {{ mustMerge .Values.pod.annotations .Values.common.annotations | toYaml | nindent 8 }}
    spec:
      containers:
        - name: openldap
          image: tiredofit/openldap:2.6
          imagePullPolicy: "IfNotPresent"
          ports: 
            - containerPort: 389
              name: ldap-port
            - containerPort: 636
              name: ldaps-port
          envFrom:
            - configMapRef:
                name: {{ tpl .Values.configMap.name . }}
          env:
            - name: ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.secret.name . }}
                  key: adminPassword
            - name: CONFIG_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.secret.name . }}      
                  key: configPassword
          volumeMounts:
            - mountPath: /var/lib/openldap
              name: pv
              subPath: data
            - mountPath: /etc/openldap/slapd.d
              name: pv
              subPath: config
            - mountPath: /assets/custom-scripts
              name: pv
              subPath: custom-scripts
            - mountPath: /certs/  
              readOnly: true
              {{- if .Values.config.enableTls }}
              name: certs
              {{- else }}
              name: pv
              subPath: certs
              {{- end }}
            - mountPath: /data/backup
              name: pv
              subPath: backup
      volumes:
        - name: pv
          persistentVolumeClaim:
            claimName: {{ tpl .Values.persistentVolumeClaim.name . }}
        {{- if .Values.config.enableTls }}
        - name: certs
          secret:
            secretName: {{ tpl .Values.certSecret.name . }}
        {{- end }}
