{{- include "common-library.secret" (dict "globals" . "override" "mailserver.secret") -}}
{{- define "mailserver.secret" -}}
data:
  adminPassword: {{ tpl .Values.config.adminPassword . | b64enc | quote }}
  configPassword: {{ tpl .Values.config.configPassword . | b64enc | quote }}
{{- end }}
