apiVersion: v1
data:
  adminPassword: {{ tpl .Values.config.adminPassword . | b64enc | quote }}
  configPassword: {{ tpl .Values.config.configPassword . | b64enc | quote }}
kind: Secret
metadata:
  name: {{ tpl .Values.secret.name . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ mustMerge .Values.secret.labels .Values.common.labels | toYaml | nindent 4 }}
  annotations: {{ mustMerge .Values.secret.annotations .Values.common.annotations | toYaml | nindent 4 }}
type: Opaque
