apiVersion: v1
data:
  adminPass: V1U3aTNSYm53ekR1SnM=
  configPass: V1U3aTNSYm53ekR1SnM=
kind: Secret
metadata:
  name: {{ tpl .Values.secret.name . }}
  namespace: {{ .Values.common.namespace }}
  labels: {{ mustMerge .Values.secret.labels .Values.common.labels | toYaml | nindent 4}}
type: Opaque
