apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.service.name . }}
  namespace: {{ .Values.common.namespace }}
  labels: {{ mustMerge .Values.service.labels .Values.common.labels | toYaml | nindent 4}}
  annotations: {{ mustMerge .Values.service.annotations .Values.common.annotations | toYaml | nindent 4 }}
spec:
  ports:
    - port: 389
      protocol: TCP
      name: ldap-port
      targetPort: ldap-port
    - port: 636
      protocol: TCP
      name: ldaps-port
      targetPort: ldaps-port
  selector: {{ tpl .Values.service.selectors . | nindent 4 }}