{{- if .Values.serviceAccount.create -}}
{{- include "common-library.serviceAccount" (dict "globals" . "override" "openldap.serviceAccount") -}}
{{- end -}}
{{- define "openldap.serviceAccount" -}}
{{- end -}}