{{- if .Values.storageClass.create -}}
{{- include "common-library.storageClass" (dict "globals" . "override" "openldap.storageClass") -}}
{{- end -}}
{{- define "openldap.storageClass" -}}
{{- end }}