{{- include "common-library.deployment" (dict "globals" . "override" "radicale.deployment") -}}
{{- define "radicale.deployment" -}}
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}:{{ tpl .Values.image.tag . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{ if .Values.config.tls.enable -}}
            - containerPort: 8443
              name: https
            {{ else -}}
            - containerPort: 8080
              name: http
            {{- end }}
          startupProbe:
            {{- tpl (toYaml .Values.startupProbe) . | nindent 12 }}
          livenessProbe:
            {{- tpl (toYaml .Values.livenessProbe) . | nindent 12 }}
          readinessProbe:
            {{- tpl (toYaml .Values.readinessProbe) . | nindent 12 }}
          resources:
            {{- tpl (toYaml .Values.resources) . | nindent 12 }}
          volumeMounts:
            - mountPath: {{ .Values.config.storage.filesystem_folder | default "/var/lib/radicale/collections" }}
              name: pv
              subPath: collections
            - mountPath: {{ .Values.config.auth.htpasswd_filename | default "/etc/radicale/users" }}
              name: secret
              subPath: users
            - mountPath: /secrets/ssl/rsa
              readOnly: true
              {{- if .Values.config.tls.enable }}
              name: certs
              {{- else }}
              name: pv
              subPath: certs
              {{ end }}
      volumes:
        - name: pv
          persistentVolumeClaim:
            claimName: {{ tpl .Values.persistentVolumeClaim.name . }}
        {{- if .Values.config.tls.enable }}
        - name: secret
          secret:
            secretName: {{ tpl .Values.secret.name . }}
        - name: certs
          secret:
            secretName: {{ tpl .Values.certSecret.name . }}
        {{- end }}
        - name: tmp-files
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector: 
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: 
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: 
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
