{{- include "common-library.secret" (dict "globals" . "override" "radicale.secret") -}}
{{- define "radicale.secret" -}}
data:
  users: |
  {{- range .Values.config.users -}}
  {{ .name }}:{{ htpasswd .name .password }}
  {{- end }}
{{- end -}}

