{{- if .Values.serviceAccount.create -}}
{{- include "common-library.serviceAccount" (dict "globals" . "override" "radicale.serviceAccount") -}}
{{- end -}}
{{- define "radicale.serviceAccount" -}}
{{- end -}}