annotations: {}
apiVersion: v2
appVersion: "15.3"
dependencies:
  - name: common-library
    repository: file://../common-library
    version: 0.0.1
deprecated: false
description: Simple Postgres database server
home: https://www.postgresql.org/
icon: https://www.svgrepo.com/show/379134/dns.svg
keywords:
  - postgres
  - database
  - init scripts
kubeVersion: ""
maintainers:
  - email: joern.krenzer@gmx.de
    name: jkrenzer
    url: https://github.com/jkrenzer
name: postgres
sources:
  - https://github.com/postgres/postgres
type: application
version: 0.0.3
