common:
  name: postgres
  annotations: {}
  labels:
    app: postgres
configMap:
  name: ""
database:
  user: postgres
  password: ""
  defaultDbName: postgres
deployment:
  name: ""
pod:
  labels:
pv: {}
pvc: {}
scripts:
  name: ""
secret:
  name: ""
service:
  port: 5432
  name: postgres
  selectors:
    app: postgres
persistentVolume:
  create: true
  name: "{{ .Values.common.name }}-pv"
  labels: {}
  annotations: {}
  reclaimPolicy: Delete
  volumeMode: Filesystem
persistentVolumeClaim:
  name: "{{ .Values.common.name }}-pvc"
  labels: {}
  annotations: {}
storage:
  local: {}
  space: 10Gi
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  hosts:
    - localhost
storageClass:
  create: false
  name: "{{ .Values.storage.storageClassName }}"
  labels: {}
  annotations: {}
  provisioner: kubernetes.io/no-provisioner
  volumeBindingMode: WaitForFirstConsumer
